name: Sync Docker Images

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Debug Secrets
        run: |
          if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "DOCKERHUB_USERNAME is set"
          else
            echo "DOCKERHUB_USERNAME is not set"
          fi
          if [ -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "DOCKERHUB_TOKEN is set"
          else
            echo "DOCKERHUB_TOKEN is not set"
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v2  # 更新到v2版本
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Private Registry
        uses: docker/login-action@v2  # 更新到v2版本
        with:
          registry: 119.23.251.91:5000
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Sync images
        run: |
          while IFS= read -r image; do
            [ -z "$image" ] || [[ "$image" =~ ^#.* ]] && continue
            echo "Syncing $image..."
            docker pull $image
            new_image="119.23.251.91:5000/${image#*/}"
            docker tag $image $new_image
            docker push $new_image
          done < images.txt
